### ISSUE TITLE
Removal of logs

### ISSUE THREAD

**Issue by michaelcullum** [phpbb-extensions/teamsecurity#17]
Let's also add functionality where we add to the php code for `/phpbb/log/log.php`'s `delete()` method to prevent it from deleting the log entries (silently, don't error) and email the log entries attempted to be deleted to the security email. We'll need a core event in this method to be able to do this though.

**Comment by VSEphpbb** [comment]
What if they try to Delete All....That could be one huge email

**Comment by michaelcullum** [comment]
<VSE> What if they try to Delete All....That could be one huge email
<MichaelC> then say they tried to delete all

**Comment by VSEphpbb** [comment]
See PR #20
