### ISSUE TITLE
Serialize arrays with json_encode instead of serialize()

### ISSUE THREAD

**Issue by nickvergessen** [phpbb-extensions/teamsecurity#2]
`unserialize()` is potential dangerous.

**Comment by naderman** [comment]
It is if called on user input, which as far as I can see is not the case here?

**Comment by nickvergessen** [comment]
https://github.com/phpbb-extensions/teamsecurity/blob/master/acp/teamsecurity_module.php#L78

**Comment by naderman** [comment]
That is a call to serialize which is perfectly safe. And all unserialize calls are only on data that was serialized that way. What would be dangerous is `unserialize($this->request->variable('foo', '')`
