### ISSUE TITLE
Add the ability for 2-factor auth

### ISSUE THREAD

**Issue by Un1matr1x** [phpbb-extensions/teamsecurity#22]
add support (or even force to use) for 2 factor auth for groups/users/...

f.e. Google Authenticator

**Comment by michaelcullum** [comment]
This is planned eventually but might be hard to implement at present

**Comment by VSEphpbb** [comment]
Also goes beyond the scope of this extension
> This extension adds passive security features to phpBB that allow the board's founder to watch for potential attacks against members of privileged groups, such as Administrators and Moderators.
