### ISSUE TITLE
Email template

### ISSUE THREAD

**Issue by michaelcullum** [phpbb-extensions/teamsecurity#3]

**Comment by VSEphpbb** [comment]
AFAIK, this functionality is done with respect to this ext. Now we just need phpBB core to support it.

**Comment by michaelcullum** [comment]
The subject contains `phpBB.com` (Should be {SITENAME} iirc) and yes

**Comment by VSEphpbb** [comment]
Oh, so make it the way I had it originally before you had me change it :wink:
